[package]
name = "sshield"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.17", features = [ "derive" ] }
rusqlite = { version = "0.29.0", features = ["bundled"] }
russh = "0.37.1"
russh-keys = "0.37.1"
